#!/bin/bash


add_badges_to_readme(){
  local name="${get_name_from_package_json}"
  echo "" >> README.md
  echo "[![Build Status](https://travis-ci.org/octoblu/${name}.svg?branch=master)](https://travis-ci.org/octoblu/${name})" >> README.md
  echo "[![Test Coverage](https://codecov.io/gh/octoblu/${name}/branch/master/graph/badge.svg)](https://codecov.io/gh/octoblu/${name})" >> README.md
  echo "[![npm version](https://badge.fury.io/js/${name}.svg)](http://badge.fury.io/js/${name})" >> README.md
  echo "[![Slack Status](http://community-slack.octoblu.com/badge.svg)](http://community-slack.octoblu.com)" >> README.md
}

copy_templates(){
  mkdir -p test
  cp "${TEMPLATES_DIR}/mocha.opts" test/
  cp "${TEMPLATES_DIR}/test_helper.coffee" test/
  cp "${TEMPLATES_DIR}/codeclimate.yml" .codeclimate.yml
  cp "${TEMPLATES_DIR}/coffeelint.json" coffeelint.json
}

get_name_from_package_json(){
  local package_json="$(cat package.json)"
  local name="$(echo "$package_json" | jq -r '.name')"
  echo "$name"
}

get_templates_dir(){
  local hop="$BASH_SOURCE"
  local original_dir="$CWD"

  cd "$(dirname $hop)"
  while [ -n "$(readlink "${hop}")" ]; do
    hop="$(readlink "${hop}")"
    cd "$(dirname "${hop}")"
  done

  local script_directory="$(pwd)"
  cd "${original_dir}"
  echo "${script_directory}/../templates/testify"
}

install_npm_modules(){
  npm install --save-dev coffee-script mocha sinon chai sinon-chai istanbul mocha-istanbul coffee-coverage chai-subset
}

update_package_json(){
  local package_json="$(cat package.json)"
  local name="$(echo "$package_json" | jq -r '.name')"
  local revised_package_json=$(echo "$package_json" | jq 'setpath(["scripts", "test"]; "istanbul cover _mocha -- -R spec --require coffee-coverage/register-istanbul && mocha --reporter json > coverage/mocha.json")')

  echo "$revised_package_json" > package.json
}

main(){
  TEMPLATES_DIR="$(get_templates_dir)"

  install_npm_modules
  copy_templates
  travisify $@
  update_package_json
  echo "We modified your package.json 'npm test' command. Sorry?"

  echo "And now we are about to ruin your README.md #sorrynotsorry"
  grep 'Build Status' README.md &> /dev/null
  if [ $? -eq 0 ]; then
    echo "... uhh nvm."
    exit 0
  fi
  add_badges_to_readme
}
main $@
