#!/bin/bash


get_templates_dir(){
  local hop="$BASH_SOURCE"
  local original_dir="$CWD"

  cd "$(dirname $hop)"
  while [ -n "$(readlink "${hop}")" ]; do
    hop="$(readlink "${hop}")"
    cd "$(dirname "${hop}")"
  done

  local script_directory="$(pwd)"
  cd "${original_dir}"
  echo "${script_directory}/../templates/travisify"
}

get_npm_key() {
  cat "$HOME/.npmrc" | grep authToken | sed -e 's/.*_authToken=//'
}

main(){
  TEMPLATES_DIR="$(get_templates_dir)"

  echo "Updating travis config..."
  cp "${TEMPLATES_DIR}/travis.yml" .travis.yml
  travis sync $@ --no-interactive
  travis enable $@ --no-interactive
  local npm_key="$(get_npm_key)"
  travis encrypt $@ --no-interactive --add deploy.api_key "$npm_key"
}
main $@
