#!/bin/bash

get_templates_dir(){
  local hop="$BASH_SOURCE"
  local original_dir="$CWD"

  cd "$(dirname $hop)"
  while [ -n "$(readlink "${hop}")" ]; do
    hop="$(readlink "${hop}")"
    cd "$(dirname "${hop}")"
  done

  local script_directory="$(pwd)"
  cd "${original_dir}"
  echo "${script_directory}/../templates/travisify"
}

main(){
  echo "Updating travis config..."
  local templates_dir="$(get_templates_dir)"

  cp ~/Projects/Octoblu/muxblu/test/travis.yml .travis.yml
  travis sync $@ --no-interactive
  travis enable $@ --no-interactive
  travis encrypt $@ --no-interactive --add deploy.api_key ***REMOVED***
}
main $@
